RESOLVE: Issue #17 [bug] número de arquivos gerados é maior que número de municípios
emanuelucas04/ifal-qd pull request #23
Opened 2022-10-13 00:03 UTC by alex-custodio

Descobri fazendo esse código que Maragogi não foi o único que se repetiu, São Luís do Quitunde também e sem ser na mesma ordem. Então se você observar a lista nomes_arquivos ANTES das minhas modificações, ela conta com nomes repetidos, referentes às multiplas aparições de "ESTADO DE ALAGOAS" seguido de "PREFEITURA MUNICIPAL DE". 

Para resolver isso eu coloquei um if para que ele não adicionasse um nome que já existisse em nomes_arquivos. 
Depois eu criei uma estrutura de repetição for para montar o dicionário.

2022-10-13 12:38 UTC, danielfireman requested changes
Transformar `lista_nomes_municipios` em um dicionário. Dessa forma, evitamos criar outro dicionário.

2022-10-13 12:38 UTC, danielfireman commented on post_proc.py
> -
Deixar uma linha em branco para separar a estrutura de condição.

2022-10-13 12:38 UTC, danielfireman commented on post_proc.py
> +dicionario_municipios = {}
Usar nome do arquivo do município como chave do dicionário, dessa forma, simplificamos muito esse laço e o laço seguinte, que preenche os arquivos.

2022-10-14 03:39 UTC, alex-custodio commented
Boa noite professor, fiz as alterações pedidas. Tive que mudar algumas coisas que eu tinha feito como retirar aquele if que eu coloquei pra impedir nomes de arquivo repetidos, pois a lista "nomes_arquivos" é criada baseada na "lista_nomes_municipios" (linha 62), e a "lista_nomes_municipios" é construída de forma a registrar os nomes dos municípios em ordem de aparição. Dessa forma, quando há mais de uma aparição de um mesmo município, são gerados elementos repetidos, o que é bom pro nosso objetivo de usar "nomes_arquivos" como chave, já que o seu comportamento no código é concatenar o texto do município com o que já estiver naquela chave, que já que é a mesma, irá concatenar com o restante do conteúdo do município.

Coloquei também a conversão da lista de município para texto direto no "for" onde o dicionário é construído, para que eu possa concatenar. 

Tô explicando isso tudo como forma de documentar e reforçar o aprendizado também.

Tenha uma boa noite, professor Daniel!

2022-10-14 13:38 UTC, danielfireman approved these changes

2022-10-14 13:38 UTC, merged