Adicionando Teste Cabeçalho
emanuelucas04/ifal-qd pull request #30
Opened 2022-10-20 19:38 UTC by alex-custodio

2022-10-20 22:43 UTC, danielfireman requested changes

2022-10-20 22:43 UTC, danielfireman commented on post_proc.py
> +def pegar_texto_diario_slice(texto_diario: str):
Por que ter um método que só é chamado uma vez e, na prática só tem uma linha?

2022-10-20 22:43 UTC, danielfireman commented on post_proc.py
> +def pegar_cabecalho(texto_diario: str):
Pegar cabeçalho só é utilizado no teste. O código deve sempre estar o mais perto possível de onde ele é usado (padrão expert). Mover para la.

2022-10-20 22:43 UTC, danielfireman commented on post_proc_test.py
> +from post_proc import *
Pode voltar apenas para extrai_diarios

2022-10-20 22:43 UTC, danielfireman commented on post_proc_test.py
> +                    cabecalho_extraido = pegar_cabecalho(
O cabeçalho deve ser checado em *todos* os diários, não?

2022-10-21 19:36 UTC, alex-custodio commented
A função "pegar cabeçalho" tornou-se obsoleta.

2022-10-21 19:44 UTC, danielfireman approved these changes

2022-10-21 19:44 UTC, merged