Deletar Preâmbulo
emanuelucas04/ifal-qd pull request #8
Opened 2022-09-21 19:39 UTC by emanuelucas04

Boa tarde!
Conseguimos remover o preâmbulo!

2022-09-21 23:21 UTC, danielfireman requested changes

2022-09-21 23:21 UTC, danielfireman commented on post_proc.py
> +aux = 0
Remover variável sem uso.

2022-09-21 23:21 UTC, danielfireman commented on post_proc.py
> +conta_linhas = 0
Remover variável. Minha sugestão abaixo torna essa variável obsoleta.

2022-09-21 23:21 UTC, danielfireman commented on post_proc.py
> +comeco_preambulo = False
```suggestion
preambulo = False
```

2022-09-21 23:21 UTC, danielfireman commented on post_proc.py
> +        expediente_linha = num_linha
```suggestion
        preambulo = True
```

2022-09-21 23:21 UTC, danielfireman commented on post_proc.py
> +            comeco_preambulo = False
```suggestion
    if preambulo:
        linhas_apagar.append(num_linha)
    
    if "gestão municipal" in linha:
        comeco_preambulo = False
```

2022-09-22 00:12 UTC, alex-custodio commented on post_proc.py
> +aux = 0
Essa variável "aux" era pra ser a declaração de "expediente_linha". Acabei de mudar com um novo commit.

2022-09-22 00:18 UTC, alex-custodio commented on post_proc.py
> +aux = 0
Vi agora que no fim vai acabar sendo removida mesmo, então dá pra desconsiderar o que eu falei.

2022-09-23 17:02 UTC, danielfireman approved these changes

2022-09-23 17:40 UTC, merged